sonar.projectKey=FabricioAlama2001_yepez-rehab-backend
sonar.organization=fabricioalama2001

sonar.projectName=Yépez Rehab Backend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
